spring:
  application:
    name: runner
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456 # Redis 服务器密码，默认为空。生产中，一定要设置 Redis 密码！
      database: 0 # Redis 数据库号，默认为 0 。
      timeout: 0 # Redis 连接超时时间，单位：毫秒。

server:
  port: 8080
